### ISSUE TITLE
Possible performance improvement

### ISSUE THREAD

**Issue by sorinvasilescu** [ronbadur/maven-artifacts-uploader#1]
Hi,
First let me start by thanking you for your great work.
I can't say I understand the code, but judging by the performance, I would assume that you are launching a separate maven process for each artifact that must be uploaded.
I'm curious whether these could be batched somehow, because on my computer it takes about 2 secs to upload each component and I'm guessing that this is just overhead from constantly starting new JVM processes.
I will keep digging, maybe I find an actual fix, but until then, I'd be glad to hear your opinion on this.
Best regards,
Sorin.

**Comment by sorinvasilescu** [comment]
One quick improvement:
`invocationRequest.setMavenOpts("-client -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xverify:none");`

Apparently, this makes the JVM/Maven processes spawn up quicker and it helps the overall upload speed.
Haven't tested each flag and all flags may not be necessary, as there is no compilation actually going on.

**Comment by sorinvasilescu** [comment]
Also, added some threads.
If you're interested, you can see it here: https://github.com/sorinvasilescu/maven-artifacts-uploader/commit/b3868806c135338be63b197d7ad4dd2a24766c52
It is a bit hacky, but it speeds up things quite significantly.

**Comment by ronbadur** [comment]
Hey First of all thanks for the feedback,  I really appreciate that. I checked your claims and you are acutally right, the maven-invoker library open a new process for each upload command. I will try to explore about solutions for our performance issue in the next few days, By the way adding few more threads is a good idea I will consider that.
Thanks,
Ron

**Comment by ronbadur** [comment]
fixed with a pull request
