### ISSUE TITLE
If one item fails, no others following it are uploaded

### ISSUE THREAD

**Issue by sorinvasilescu** [ronbadur/maven-artifacts-uploader#2]
In the stream chain:
`files.filter(pomFilePredictor).peek(xmlReformer::prepareXmlToDeploy).forEach(mavenDeployer::deployArtifact);`
if one prepareXmlToDeploy fails (let's say Null Pointer Exception), the whole stream fails and the rest of the files are not processed.

I've found the following solution:

```
files.filter(pomFilePredictor).filter(path -> {
   try {
        xmlReformer.prepareXmlToDeploy(path);
        return true;
    } catch (Exception e) {
        logger.error("Error uploading " + path + " : " + e);
        return false;
    }
}).forEach(mavenDeployer::deployArtifact);
```

I know those streams are pretty to write, but it was not uploading some 50+ assets because the first one had an error in the XML.

**Comment by ronbadur** [comment]
#3 fixed with a pull request
